version: '3'

services:
  manager:
    image: 'manager'
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PW=${DB_PW}
      - DB_PORT=5432
      - PORT=3000
      - REDIS_PORT=6379
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PW=${REDIS_PW}
      - SECS_TO_EXPIRE=1000000s
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - fana-postgres-data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD=${DB_PW}
      - PGDATA=/var/lib/postgresql/data/pgdata
  redis:
    image: redis
    hostname: my-redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PW=${REDIS_PW}
    command: redis-server --requirepass mypassword