{
  "sdkKeys":[
    "c3e-db3100c-8",
    "de9-6bf1a0c-3",
    "fa4-d731f0e-4"
  ],
  "flags":{
    "development-flag-1":{
      "beta_testers":{
        "combine":"ANY",
        "conditions":[{
          "negate":false,
          "operator":"EQ",
          "attribute":"beta",
          "vals":["true"]
        }]
      },
      "status":false
    },
    "experimental-flag-1":{
      "status":false
    },
    "fake-flag-1":{
      "california_students":{
        "combine":"ANY",
        "conditions":[
          {
            "negate":false,
            "operator":"EQ",
            "attribute":"state",
            "vals":["california"]
          },
          {
            "negate":false,
            "operator":"EQ",
            "attribute":"student",
            "vals":["true"]
          }
        ]
      },
      "status":false
    }
  }
}