POST http://localhost:6000/api/attributes HTTP/1.1
content-type: application/json

{
    "key": "country",
    "displayName": "Country",
    "attrType": "STR"
}

###

POST http://localhost:6000/api/attributes HTTP/1.1
content-type: application/json

{
    "key": "employed",
    "displayName": "Employeeeet",
    "attrType": "BOOL"
}

###

POST http://localhost:6000/api/attributes HTTP/1.1
content-type: application/json

{
    "key": "omega",
    "displayName": "300 Diver",
    "attrType": "BOOL"
}

###

POST http://localhost:6000/api/attributes HTTP/1.1
content-type: application/json

{
    "key": "age",
    "displayName": "Age",
    "attrType": "NUM"
}

###

POST http://localhost:6000/api/audiences HTTP/1.1
content-type: application/json

{
    "key": "texas_students",
    "displayName": "TX Students",
    "combine": "ALL",
    "conditions": [
        {
        "attributeID": 1,
        "operator": "EQ",
        "vals": "texas"
        },
        {
        "attributeID": 2,
        "operator": "EQ",
        "vals": "true"
        }        
    ]
}

###

POST http://localhost:6000/api/audiences HTTP/1.1
content-type: application/json

{
    "key": "nors",
    "displayName": "Norwegians",
    "combine": "ANY",
    "conditions": [
        {
        "attributeID": 1,
        "operator": "EQ",
        "negate": false,
        "vals": "california"
        },
        {
        "attributeID": 3,
        "operator": "EQ",
        "vals": "true"
        }        
    ]
}

###

POST http://localhost:6000/api/audiences HTTP/1.1
content-type: application/json

{
    "key": "cali_students",
    "diaplayName": "CA Students",
    "combine": "ALL",
    "conditions": [
        {
        "attributeID": 1,
        "negate": false,
        "operator": "EQ",
        "vals": "california"
        },
        {
        "attributeID": 2,
        "negate": false,
        "operator": "EQ",
        "vals": "true"
        }        
    ]
}

###

POST http://localhost:6000/api/flags HTTP/1.1
content-type: application/json

{
    "key": "fake-flag-2",
    "displayName": "Fake Flag 2",
    "sdkKey": "beta_sdk_0",
    "audiences": ["california_students", "beta_testers"]
}

###

POST http://localhost:6000/api/flags HTTP/1.1
content-type: application/json

{
    "key": "inauthentic_flag_2",
    "displayName": "Inauthentic Flag 2",
    "sdkKey": "beta_sdk_0",
    "audiences": []
}

###

PATCH http://localhost:6000/api/flags/1 HTTP/1.1
content-type: application/json

{
    "displayName": "Is a real flag",
    "audiences": []
}

###

PATCH http://localhost:6000/api/flags/1/toggle HTTP/1.1
content-type: application/json

{
    "status": true
}

###

PATCH http://localhost:6000/api/flags/2/toggle HTTP/1.1
content-type: application/json

{
    "status": false
}

###

PATCH http://localhost:6000/api/audiences/1 HTTP/1.1
content-type: application/json

{
  "displayName": "Betaaa",
  "combine": "ALL",
  "conditions": [
      {
      "attributeID": 1,
      "operator": "EQ",
      "vals": "texas"
      },
      {
      "attributeID": 2,
      "operator": "EQ",
      "vals": "true",
      "negate": true
      }        
  ]
}

###

GET http://localhost:6000/api/flags HTTP/1.1

###

GET http://localhost:6000/flagset HTTP/1.1

###

GET http://localhost:6000/api/flags/1 HTTP/1.1

###

GET http://localhost:6000/api/attributes HTTP/1.1

###

GET http://localhost:6000/api/attributes/1 HTTP/1.1

###

GET http://localhost:6000/api/audiences HTTP/1.1

###

GET http://localhost:6000/api/audiences/1 HTTP/1.1

###

GET http://localhost:6000/api/auditlogs HTTP/1.1

###

GET http://localhost:6000/api/sdkkeys HTTP/1.1

###

DELETE http://localhost:6000/api/flags/1 HTTP/1.1

###

DELETE http://localhost:6000/api/audiences/1 HTTP/1.1

###

DELETE http://localhost:6000/api/attributes/1 HTTP/1.1

###

POST http://localhost:6000/api/sdkkeys/yournamehere HTTP/1.1

###