POST http://localhost:6000/api/attributes HTTP/1.1
content-type: application/json

{
    "key": "country",
    "attrType": "STR"
}

###

POST http://localhost:6000/api/attributes HTTP/1.1
content-type: application/json

{
    "key": "employed",
    "attrType": "BOOL"
}

###

POST http://localhost:6000/api/attributes HTTP/1.1
content-type: application/json

{
    "key": "omega",
    "attrType": "BOOL"
}

###

POST http://localhost:6000/api/attributes HTTP/1.1
content-type: application/json

{
    "key": "age",
    "attrType": "NUM"
}

###

POST http://localhost:6000/api/audiences HTTP/1.1
content-type: application/json

{
    "key": "texas_students",
    "combine": "ALL",
    "conditions": [
        {
        "attributeID": 1,
        "operator": "EQ",
        "vals": "texas"
        },
        {
        "attributeID": 2,
        "operator": "EQ",
        "vals": "true"
        }        
    ]
}

###

POST http://localhost:6000/api/audiences HTTP/1.1
content-type: application/json

{
    "key": "Beta Testers",
    "combine": "ANY",
    "conditions": [
        {
        "attribute": 1,
        "operator": "EQ",
        "vals": "california"
        },
        {
        "attribute": 3,
        "operator": "EQ",
        "vals": "true"
        }        
    ]
}

###

POST http://localhost:6000/api/audiences HTTP/1.1
content-type: application/json

{
    "key": "cali_students",
    "combine": "ALL",
    "conditions": [
        {
        "attribute": "state",
        "operator": "EQ",
        "vals": "california"
        },
        {
        "attribute": "student",
        "operator": "EQ",
        "vals": "true"
        }        
    ]
}

###

POST http://localhost:6000/api/flags HTTP/1.1
content-type: application/json

{
    "key": "Fake Flag 1",
    "sdkKey": "beta_sdk_0",
    "audiences": ["cali_students", "beta_testers"]
}

###

POST http://localhost:6000/api/flags HTTP/1.1
content-type: application/json

{
    "key": "Inauthentic_Flag_2",
    "displayName": "Inauthentic Flag 2",
    "sdkKey": "beta_sdk_0",
    "audiences": [1, 2]
}

###

PATCH http://localhost:6000/api/flags/1/toggle HTTP/1.1
content-type: application/json

{
    "status": true
}

###

PATCH http://localhost:6000/api/flags/2/toggle HTTP/1.1
content-type: application/json

{
    "status": true
}

###

GET http://localhost:6000/api/flags HTTP/1.1

###

GET http://localhost:6000/api/flags/2 HTTP/1.1

###

GET http://localhost:6000/api/attributes HTTP/1.1

###

GET http://localhost:6000/api/attributes/1 HTTP/1.1

###

GET http://localhost:6000/api/audiences HTTP/1.1

###

GET http://localhost:6000/api/audiences/1 HTTP/1.1