// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: fana.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FanaClient is the client API for Fana service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FanaClient interface {
	GetFlag(ctx context.Context, in *ID, opts ...grpc.CallOption) (*FlagFullResp, error)
	GetFlags(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Flags, error)
	GetAudience(ctx context.Context, in *ID, opts ...grpc.CallOption) (*AudienceFullResp, error)
	GetAudiences(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Audiences, error)
	GetAttribute(ctx context.Context, in *ID, opts ...grpc.CallOption) (*AttributeResp, error)
	GetAttributes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Attributes, error)
	CreateFlag(ctx context.Context, in *FlagSubmit, opts ...grpc.CallOption) (*FlagFullResp, error)
	CreateAudience(ctx context.Context, in *AudSubmit, opts ...grpc.CallOption) (*AudienceFullResp, error)
	CreateAttribute(ctx context.Context, in *AttrSubmit, opts ...grpc.CallOption) (*AttributeResp, error)
}

type fanaClient struct {
	cc grpc.ClientConnInterface
}

func NewFanaClient(cc grpc.ClientConnInterface) FanaClient {
	return &fanaClient{cc}
}

func (c *fanaClient) GetFlag(ctx context.Context, in *ID, opts ...grpc.CallOption) (*FlagFullResp, error) {
	out := new(FlagFullResp)
	err := c.cc.Invoke(ctx, "/Fana/GetFlag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fanaClient) GetFlags(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Flags, error) {
	out := new(Flags)
	err := c.cc.Invoke(ctx, "/Fana/GetFlags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fanaClient) GetAudience(ctx context.Context, in *ID, opts ...grpc.CallOption) (*AudienceFullResp, error) {
	out := new(AudienceFullResp)
	err := c.cc.Invoke(ctx, "/Fana/GetAudience", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fanaClient) GetAudiences(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Audiences, error) {
	out := new(Audiences)
	err := c.cc.Invoke(ctx, "/Fana/GetAudiences", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fanaClient) GetAttribute(ctx context.Context, in *ID, opts ...grpc.CallOption) (*AttributeResp, error) {
	out := new(AttributeResp)
	err := c.cc.Invoke(ctx, "/Fana/GetAttribute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fanaClient) GetAttributes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Attributes, error) {
	out := new(Attributes)
	err := c.cc.Invoke(ctx, "/Fana/GetAttributes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fanaClient) CreateFlag(ctx context.Context, in *FlagSubmit, opts ...grpc.CallOption) (*FlagFullResp, error) {
	out := new(FlagFullResp)
	err := c.cc.Invoke(ctx, "/Fana/CreateFlag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fanaClient) CreateAudience(ctx context.Context, in *AudSubmit, opts ...grpc.CallOption) (*AudienceFullResp, error) {
	out := new(AudienceFullResp)
	err := c.cc.Invoke(ctx, "/Fana/CreateAudience", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fanaClient) CreateAttribute(ctx context.Context, in *AttrSubmit, opts ...grpc.CallOption) (*AttributeResp, error) {
	out := new(AttributeResp)
	err := c.cc.Invoke(ctx, "/Fana/CreateAttribute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FanaServer is the server API for Fana service.
// All implementations must embed UnimplementedFanaServer
// for forward compatibility
type FanaServer interface {
	GetFlag(context.Context, *ID) (*FlagFullResp, error)
	GetFlags(context.Context, *Empty) (*Flags, error)
	GetAudience(context.Context, *ID) (*AudienceFullResp, error)
	GetAudiences(context.Context, *Empty) (*Audiences, error)
	GetAttribute(context.Context, *ID) (*AttributeResp, error)
	GetAttributes(context.Context, *Empty) (*Attributes, error)
	CreateFlag(context.Context, *FlagSubmit) (*FlagFullResp, error)
	CreateAudience(context.Context, *AudSubmit) (*AudienceFullResp, error)
	CreateAttribute(context.Context, *AttrSubmit) (*AttributeResp, error)
	mustEmbedUnimplementedFanaServer()
}

// UnimplementedFanaServer must be embedded to have forward compatible implementations.
type UnimplementedFanaServer struct {
}

func (UnimplementedFanaServer) GetFlag(context.Context, *ID) (*FlagFullResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlag not implemented")
}
func (UnimplementedFanaServer) GetFlags(context.Context, *Empty) (*Flags, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlags not implemented")
}
func (UnimplementedFanaServer) GetAudience(context.Context, *ID) (*AudienceFullResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAudience not implemented")
}
func (UnimplementedFanaServer) GetAudiences(context.Context, *Empty) (*Audiences, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAudiences not implemented")
}
func (UnimplementedFanaServer) GetAttribute(context.Context, *ID) (*AttributeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttribute not implemented")
}
func (UnimplementedFanaServer) GetAttributes(context.Context, *Empty) (*Attributes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttributes not implemented")
}
func (UnimplementedFanaServer) CreateFlag(context.Context, *FlagSubmit) (*FlagFullResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFlag not implemented")
}
func (UnimplementedFanaServer) CreateAudience(context.Context, *AudSubmit) (*AudienceFullResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAudience not implemented")
}
func (UnimplementedFanaServer) CreateAttribute(context.Context, *AttrSubmit) (*AttributeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAttribute not implemented")
}
func (UnimplementedFanaServer) mustEmbedUnimplementedFanaServer() {}

// UnsafeFanaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FanaServer will
// result in compilation errors.
type UnsafeFanaServer interface {
	mustEmbedUnimplementedFanaServer()
}

func RegisterFanaServer(s grpc.ServiceRegistrar, srv FanaServer) {
	s.RegisterService(&Fana_ServiceDesc, srv)
}

func _Fana_GetFlag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FanaServer).GetFlag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Fana/GetFlag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FanaServer).GetFlag(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fana_GetFlags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FanaServer).GetFlags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Fana/GetFlags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FanaServer).GetFlags(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fana_GetAudience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FanaServer).GetAudience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Fana/GetAudience",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FanaServer).GetAudience(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fana_GetAudiences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FanaServer).GetAudiences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Fana/GetAudiences",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FanaServer).GetAudiences(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fana_GetAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FanaServer).GetAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Fana/GetAttribute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FanaServer).GetAttribute(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fana_GetAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FanaServer).GetAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Fana/GetAttributes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FanaServer).GetAttributes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fana_CreateFlag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlagSubmit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FanaServer).CreateFlag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Fana/CreateFlag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FanaServer).CreateFlag(ctx, req.(*FlagSubmit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fana_CreateAudience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AudSubmit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FanaServer).CreateAudience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Fana/CreateAudience",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FanaServer).CreateAudience(ctx, req.(*AudSubmit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fana_CreateAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttrSubmit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FanaServer).CreateAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Fana/CreateAttribute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FanaServer).CreateAttribute(ctx, req.(*AttrSubmit))
	}
	return interceptor(ctx, in, info, handler)
}

// Fana_ServiceDesc is the grpc.ServiceDesc for Fana service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Fana_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Fana",
	HandlerType: (*FanaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFlag",
			Handler:    _Fana_GetFlag_Handler,
		},
		{
			MethodName: "GetFlags",
			Handler:    _Fana_GetFlags_Handler,
		},
		{
			MethodName: "GetAudience",
			Handler:    _Fana_GetAudience_Handler,
		},
		{
			MethodName: "GetAudiences",
			Handler:    _Fana_GetAudiences_Handler,
		},
		{
			MethodName: "GetAttribute",
			Handler:    _Fana_GetAttribute_Handler,
		},
		{
			MethodName: "GetAttributes",
			Handler:    _Fana_GetAttributes_Handler,
		},
		{
			MethodName: "CreateFlag",
			Handler:    _Fana_CreateFlag_Handler,
		},
		{
			MethodName: "CreateAudience",
			Handler:    _Fana_CreateAudience_Handler,
		},
		{
			MethodName: "CreateAttribute",
			Handler:    _Fana_CreateAttribute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fana.proto",
}
